site_name: Rust Notes
theme:
  name: 'material'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: Roboto Mono
  logo: assets/logo.png
  features:
    - navigation.sections
markdown_extensions:
  - attr_list
  - md_in_html
copyright: Made with ❤️ in Vancouver
extra:
  social:
    - icon: fontawesome/brands/canadian-maple-leaf
      link: https://karthikaiyasamy.github.io/rustnotes/
      name: Made in Canada

